name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [26, 27, 28]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache Hex packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/rebar3/hex/hexpm/packages
        key: ${{ runner.os }}-hex-${{ hashFiles(format('{0}{1}', github.workspace, '/rebar.lock')) }}
        restore-keys: |
          ${{ runner.os }}-hex-
    - name: Compile
      run: rebar3 compile
    - name: Run EUnit Tests
      run: rebar3 eunit
    - name: Run Dialyzer
      run: rebar3 dialyzer
