name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: '19.3.6.13'
            rebar: '3.6.1'
          - otp: '21.3.8.23'
            rebar: '3.6.1'
          - otp: '24.0'
            rebar: '3.18.0'
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar}}
      - name: Compile
        run: rebar3 compile
      - name: Run EUnit Tests
        run: rebar3 eunit
